undef $/ ;
while (<>) {
	s/\x{e2}\x{80}\x{99}/\'/g ;
	s/\x{e2}\x{80}\x{98}/\'/g ;
	s/\x{e2}\x{80}\x{9d}/\"/g ;
	s/\x{e2}\x{80}\x{8b}//g ;
	s/\x{e2}\x{80}\x{90}/-/g;
	s/\o{342}\o{200}\o{223}//g ;
	s/\o{342}\o{200}\o{246}/.../g ;
	s/\x{e2}\x{80}\x{9c}/\"/g ;
	s/\x{e2}\x{9d}\x{96}/*/g ;
	s/\x{e2}\x{97}\x{8f}/*/g ;
	s/\x{c2}\x{ad}/-/g ;
	s/\x{c2}\x{bc}/1\/4/g ;
	s/\x{c2}\x{bd}/1\/2/g ;
	s/\x{c2}\x{b0}/ degrees/g ;
	s/\nSp\necial/\nSpecial/igs ;
	s/\nWe\napon/\nWeapon/igs ;
	s/Special Rules:\n/Special Rules: /igs ;
	s/Special Rule:\n/Special Rules: /igs ;	
	s/\nWA\nR /\nWAR /igs ;
	s/\nVa\nmpiric /\nVampiric /igs ;
	s/\nRA\nRE\n/\nRARE\n/igs ;
	s/\nArmour:\n/\nArmour: /igs ;
	s/\nWeapon:\n/\nWeapons: /igs ;
	s/\nMagic:\n/\nMagic: /igs ;
	s/\nWeapons:\n/\nWeapons: /igs ;
	s/ :/:/g ;
	s/\'\'/\"/g ;
	s/  / /g ;
	s/ $// ;
	print $_;
}